### ISSUE TITLE
İs it possible to make LTE Role?

### ISSUE THREAD

**Issue by BedrettinOrtak** [jhonnybonny/LTE_HACKRF#2]
Hello, I would have some questions about your project? In this project, a hackrf is used as a base station, but is it possible to make a role with another hackrf? How can we provide lte connection between 2 hackrf. Does this project have such a detail?

**Comment by jhonnybonny** [comment]
Go to xss.is

**Comment by BedrettinOrtak** [comment]
the site is in Russian and I don't speak Russian. can you help me
